import './App.css'

function App() {
  return (
    <div>
      <h1>HARRY'S BEAUTIFUL SPECTACULAR AMAZING SUPERB AWESOME INCREDIBLE INCOMPREHENSIBLE SCINTILATING UNBELIEVABLE AWE-INSPIRING AND REDICULOUSLY POORLY SPELLED AND UNREASONABLY SILLY MONSTER BATTLE ARENA!!!</h1>
    </div>
  )
}

export default App
